### ISSUE TITLE
can't run wine in proot

### ISSUE THREAD

**Issue by jinshulumengchuang** [FEX-Emu/FEX#2071]
when i try to run 'winecfg', it cashes with 'Segmentation fault'.

my os: android 12 with ubuntu 22.04 (proot)
fex version: 2210(fex-emu-armv8.0)

Thanks.

**Comment by Sonicadvance1** [comment]
This is likely just an issue of trying to run things in an Android/Proot environment. Not sure what we can do here.

**Comment by jinshulumengchuang** [comment]
after some specia

**Comment by jinshulumengchuang** [comment]
set Force32BitAllocator=1 can solve this problem

**Comment by Sonicadvance1** [comment]
Oh! I think I know the reason for this. It looks like your kernel is too old. FEX-Emu needs kernel 5.0 minimum otherwise issues can occur. A ton of Android devices are stuck on 4.19 or older.

**Comment by Sonicadvance1** [comment]
Granted, most issues should be fixed with Kernel 4.17, but we've never tested farther back than that.

**Comment by jinshulumengchuang** [comment]
> Oh! I think I know the reason for this. It looks like your kernel is too old. FEX-Emu needs kernel 5.0 minimum otherwise issues can occur. A ton of Android devices are stuck on 4.19 or older.

hello ,
my kernel version is 5.x,and termux's FEX do not have this issue (but have stuck issues,still don't have solution)

**Comment by FussyCone** [comment]
Here my phone specs:

-motorola edge 30 fusion

-Android 12

-Kernel 5.4.180-moto-gfd0f151e8b97
#1 Wed Mar 1 05:26:44 CST 2023


Same problem here :/
Segmentation fault using FEXBash or FEXInterpreter 
Did you manage to solve this?

**Comment by FussyCone** [comment]
> set Force32BitAllocator=1 can solve this problem

 No Bro. I do this and still error
