### ISSUE TITLE
Failure to setup client after installation

### ISSUE THREAD

**Issue by orende** [FEX-Emu/FEX#4329]
**Describe the bug**
After installing Fex on my arm64 laptop (Lenovo Yoga Slim7x) running Ubuntu Concept 24.10, choosing the Ubuntu 24.04 SquashFS, using it as-is and setting it as the default, the "trying basic program run" step fails with the following error message:

> FEX is now installed. Trying basic program run
> [ERROR] Couldn't connect to FEXServer socket 1000.FEXServer.Socket 111
> [ERROR] Couldn't connect to FEXServer socket /run/user/1000/1000.FEXServer.Socket 111
> [ERROR] Couldn't connect to FEXServer socket 1000.FEXServer.Socket 111
> [ERROR] Couldn't connect to FEXServer socket /run/user/1000/1000.FEXServer.Socket 111
> [ERROR] Couldn't connect to FEXServer socket 1000.FEXServer.Socket 111
> [ERROR] Couldn't connect to FEXServer socket /run/user/1000/1000.FEXServer.Socket 111
> [ERROR] Couldn't connect to FEXServer socket 1000.FEXServer.Socket 111
> [ERROR] Couldn't connect to FEXServer socket /run/user/1000/1000.FEXServer.Socket 111
> [ERROR] Couldn't connect to FEXServer socket 1000.FEXServer.Socket 111
> [ERROR] Couldn't connect to FEXServer socket /run/user/1000/1000.FEXServer.Socket 111
> [ERROR] Couldn't connect to FEXServer socket 1000.FEXServer.Socket after launching the process
> [ERROR] FEXServerClient: Failure to setup client
> FEXInterpreter failed to run. Not continuing
   

**To Reproduce**
1. Have a Lenovo Yoga Slim7x laptop running Ubuntu Concept 24.10.
2. Run the installer with `curl --silent https://raw.githubusercontent.com/FEX-Emu/FEX/main/Scripts/InstallFEX.py --output /tmp/InstallFEX.py && python3 /tmp/InstallFEX.py && rm /tmp/InstallFEX.py`
3. Select `Ubuntu 24.04 (SquashFS)` in the RootFS selection step.
4. Use the squashFS file as-is (option 2).
5. Set Ubuntu_24_04.sqsh as the default RootFS.
6. Installer crashes with above error.

**Expected behavior**
Expected basic program run to succeed.

**Screenshots and Video**
N/A.

**System information:**
 - OS: Ubuntu Concept 24.10
 - CPU/SoC: Snapdragon X1 Elite
 - Video driver version: N/A (yes, really! no Adreno X1-85 gfx driver released for linux yet)
 - RootFS used: Ubuntu 24.04 (SquashFS)
 - FEX version: FEX-2501
 - Thunks Enabled: Don't know.

**Additional context**
 - Is this an x86 or x86-64 game: N/A
 - Does this reproduce on AArch64 with Radeon/Intel/Nvidia: Untested
 - Is this a Vulkan game: No

> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 24.10
> Release:	24.10
> Codename:	oracular

> $ uname -a
> Linux ola-Yoga-Slim-7-14Q8X9 6.12.0-28-qcom-x1e #28-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 24 03:56:34 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux

**Comment by pmatos** [comment]
Hi - I have seen this before as well with Ubuntu Concept running FEX for the first time. I fixed it but tbh I forgot how. I will try to reproduce again but I wonder if adding myself to some admin groups was what fixed the issue.

Curious though. If you open a `FEXServer -f -p` on a cmd and then try on another `FEXInterpreter /usr/bin/true`, will that work?

**Comment by orende** [comment]
@pmatos I just tried this and it generated no output 🤔 The `FEXServer -f -p` command started and is running without logs, while the `FEXInterpreter /usr/bin/true` command started and exited with status code 0.

**Comment by orende** [comment]
@pmatos @Sonicadvance1  I've updated to the latest versions now:

```
> fex-emu-armv8.4/oracular,now 2502~o arm64 [installed]
> fex-emu-binfmt32/oracular,now 2502~o arm64 [installed]
> fex-emu-binfmt64/oracular,now 2502~o arm64 [installed]
```

But unfortunately, the problem persists.

**Comment by Sonicadvance1** [comment]
> [@pmatos](https://github.com/pmatos) [@Sonicadvance1](https://github.com/Sonicadvance1) I've updated to the latest versions now:
> 
> ```
> > fex-emu-armv8.4/oracular,now 2502~o arm64 [installed]
> > fex-emu-binfmt32/oracular,now 2502~o arm64 [installed]
> > fex-emu-binfmt64/oracular,now 2502~o arm64 [installed]
> ```
> 
> But unfortunately, the problem persists.

The fix for this issue was merged the day after the 2502 release. So the fix will be in FEX-2503

**Comment by orende** [comment]
> > [@pmatos](https://github.com/pmatos) [@Sonicadvance1](https://github.com/Sonicadvance1) I've updated to the latest versions now:
> > ```
> > > fex-emu-armv8.4/oracular,now 2502~o arm64 [installed]
> > > fex-emu-binfmt32/oracular,now 2502~o arm64 [installed]
> > > fex-emu-binfmt64/oracular,now 2502~o arm64 [installed]
> > ```
> >   
> > But unfortunately, the problem persists.
> 
> The fix for this issue was merged the day after the 2502 release. So the fix will be in FEX-2503

Ah, got it. I didn't read the timestamps closely enough 😅 Will try again once 2503 is out and report back.

**Comment by orende** [comment]
Can report that Fex starts up without issues on my Yoga Slim 7x after the 2503 release. Unfortunately, there are other issues, seemingly related to missing gfx drivers that will hopefully get ironed out over time. But thanks for the fix!

**Comment by Sonicadvance1** [comment]
> Can report that Fex starts up without issues on my Yoga Slim 7x after the 2503 release. Unfortunately, there are other issues, seemingly related to missing gfx drivers that will hopefully get ironed out over time. But thanks for the fix!

I think I updated the Ubuntu image to have a new enough version of mesa for x1e's GPU. Might need to download the new one.
